[versions]
minSdk = "26"
compileSdk = "36"

agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
material3 = "1.5.0-alpha08"
material3Nav = "1.4.0"
material = "1.13.0"
material-icons-core = "1.7.8"
material-icons-extended = "1.7.8"

coilComposeVersion = "2.7.0"
ktorVersion = "3.3.2"
navVersion = "2.9.6"
hilt = "2.57.2"
hiltNavigation = "1.3.0"
coreSplashscreen = "1.2.0"
uiTextGoogleFonts = "1.9.4"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref ="hiltNavigation" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorVersion" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }

# Android
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Material 3
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref="material3"}
androidx-material = { group = "com.google.android.material", name = "material", version.ref="material"}
androidx-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref="material3"}
androidx-material3-nav = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref="material3Nav"}

# Icons
material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "material-icons-core" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }

# Google Fonts
androidx-compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]
compose = [
    "androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling-preview", "androidx-material3", "compose-foundation"
]
material = ["material-icons-core","material-icons-extended","androidx-material","androidx-material3","androidx-material3-window","androidx-material3-nav"]
ktor = [
    "ktor-client-core", "ktor-client-okhttp", "ktor-client-logging",
    "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"
]